using System;
using System.Linq;
using Autodesk.Revit.DB;
using Autodesk.Revit.UI;
using RevitVersionControl.Services;

namespace RevitVersionControl.UI
{
    internal class DiffMergeApplyRequest
    {
        public string ProjectId { get; set; }
        public string TargetCommitId { get; set; }
        public string ModelId { get; set; }
        public System.Collections.Generic.List<Change> Changes { get; set; }
    }

    internal class DiffMergeApplyHandler : IExternalEventHandler
    {
        private DiffMergeApplyRequest _pendingRequest;

        public void Queue(DiffMergeApplyRequest request)
        {
            _pendingRequest = request;
        }

        public void Execute(UIApplication app)
        {
            var request = _pendingRequest;
            _pendingRequest = null;
            if (request == null)
                return;

            var uidoc = app?.ActiveUIDocument;
            var doc = uidoc?.Document;
            if (doc == null)
            {
                TaskDialog.Show("Apply Selected", "No active Revit document is available.");
                return;
            }

            if (request.Changes == null || request.Changes.Count == 0)
            {
                TaskDialog.Show("Apply Selected", "No changes selected.");
                return;
            }

            string projectId = request.ProjectId
                ?? DocumentSyncStateService.GetState(doc.PathName)?.ProjectId;

            if (!PayloadSupportService.EnsurePayloadsAvailable(projectId, request.Changes, out string payloadError))
            {
                TaskDialog.Show("Apply Selected", payloadError);
                return;
            }

            var applier = new ElementApplier(doc, projectId);
            var result = applier.ApplyChanges(request.Changes);
            if (!result.Success)
            {
                string errorMessage = "Failed to apply changes:\n\n";
                if (result.Errors.Count > 0)
                {
                    errorMessage += string.Join("\n", result.Errors.Take(5));
                    if (result.Errors.Count > 5)
                        errorMessage += $"\n\n... and {result.Errors.Count - 5} more errors";
                }
                else
                {
                    errorMessage += "Unknown error occurred.";
                }

                TaskDialog.Show("Error", errorMessage);
                return;
            }

            if (!string.IsNullOrWhiteSpace(projectId) && !string.IsNullOrWhiteSpace(request.TargetCommitId))
            {
                string modelId = !string.IsNullOrWhiteSpace(request.ModelId)
                    ? request.ModelId
                    : DocumentSyncStateService.GetStateForProject(doc.PathName, projectId)?.ModelId
                      ?? doc.PathName;
                DocumentSyncStateService.SaveState(doc.PathName, projectId, modelId, request.TargetCommitId);

                try
                {
                    var extractor = new ElementExtractor(doc);
                    var extractionOptions = new ExtractionOptions
                    {
                        BatchSize = 200,
                        PauseMilliseconds = 10,
                        IncludeGeometry = true,
                        LogProgress = true
                    };
                    var currentElements = extractor.ExtractAllElements(extractionOptions);
                    var cachedSnapshot = new ElementSnapshot
                    {
                        Version = "1.0",
                        ProjectId = projectId,
                        ModelId = modelId,
                        Timestamp = DateTime.UtcNow,
                        UserName = app.Application.Username,
                        CommitMessage = $"Cached after pane apply to {request.TargetCommitId}",
                        Elements = currentElements.Cast<object>().ToList(),
                        ParentCommit = request.TargetCommitId
                    };
                    SnapshotCacheService.SaveSnapshot(projectId, modelId, request.TargetCommitId, cachedSnapshot);
                }
                catch
                {
                }
            }

            bool hasIssues = result.Errors.Count > 0
                             || result.Warnings.Count > 0
                             || result.UnsupportedElements.Count > 0
                             || result.IgnoredAutogenerated.Count > 0;

            TaskDialog.Show(
                hasIssues ? "Completed with issues" : "Success",
                ApplyResultMessageBuilder.Build(result, 2));
        }

        public string GetName()
        {
            return "Diff Merge Apply Handler";
        }
    }
}
