using System;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Media;
using System.Collections.Generic;
using System.Linq;
using System.ComponentModel;
using RevitVersionControl.Services;
using Autodesk.Revit.UI;

namespace RevitVersionControl.UI
{
    public partial class DiffMergePane : Page
    {
        private List<Change> _currentChanges = new List<Change>();
        private Autodesk.Revit.DB.Document _currentDocument;

        public DiffMergePane()
        {
            InitializeComponent();
        }

        public void SetDocument(Autodesk.Revit.DB.Document doc)
        {
            _currentDocument = doc;
        }

        public void LoadDiffResult(DiffResult diffResult)
        {
            if (diffResult == null) { Clear(); return; }

            BaseCommitText.Text = diffResult.BaseVersion ?? "-";
            TargetCommitText.Text = diffResult.TargetVersion ?? "-";

            int added = diffResult.Summary != null && diffResult.Summary.ContainsKey("added") ? diffResult.Summary["added"] : 0;
            int modified = diffResult.Summary != null && diffResult.Summary.ContainsKey("modified") ? diffResult.Summary["modified"] : 0;
            int deleted = diffResult.Summary != null && diffResult.Summary.ContainsKey("deleted") ? diffResult.Summary["deleted"] : 0;

            AddedCountText.Text = added.ToString();
            ModifiedCountText.Text = modified.ToString();
            DeletedCountText.Text = deleted.ToString();

            _currentChanges = diffResult.Changes ?? new List<Change>();
            ChangesListView.ItemsSource = BuildChangeItems(_currentChanges);
        }

        public void LoadPullResult(PullResult pullResult)
        {
            if (pullResult == null) { Clear(); return; }

            BaseCommitText.Text = "-";
            TargetCommitText.Text = "-";

            var summary = Summarize(pullResult.Changes);
            AddedCountText.Text = summary.added.ToString();
            ModifiedCountText.Text = summary.modified.ToString();
            DeletedCountText.Text = summary.deleted.ToString();

            _currentChanges = pullResult.Changes ?? new List<Change>();
            ChangesListView.ItemsSource = BuildChangeItems(_currentChanges);
        }

        public void Clear()
        {
            BaseCommitText.Text = "-";
            TargetCommitText.Text = "-";
            AddedCountText.Text = "0";
            ModifiedCountText.Text = "0";
            DeletedCountText.Text = "0";
            ChangesListView.ItemsSource = null;
            _currentChanges.Clear();
        }

        private void SelectAll_Click(object sender, RoutedEventArgs e)
        {
            var items = ChangesListView.ItemsSource as List<ChangeItem>;
            if (items == null) return;
            foreach (var item in items)
                item.IsSelected = true;
            ChangesListView.Items.Refresh();
        }

        private void DeselectAll_Click(object sender, RoutedEventArgs e)
        {
            var items = ChangesListView.ItemsSource as List<ChangeItem>;
            if (items == null) return;
            foreach (var item in items)
                item.IsSelected = false;
            ChangesListView.Items.Refresh();
        }

        private void Highlight_Click(object sender, RoutedEventArgs e)
        {
            MessageBox.Show("Highlight in View is not yet implemented.", "Info",
                MessageBoxButton.OK, MessageBoxImage.Information);
        }

        private void ApplySelected_Click(object sender, RoutedEventArgs e)
        {
            var items = ChangesListView.ItemsSource as List<ChangeItem>;
            if (items == null || !items.Any(i => i.IsSelected))
            {
                MessageBox.Show("No changes selected.", "Apply Selected",
                    MessageBoxButton.OK, MessageBoxImage.Warning);
                return;
            }

            if (_currentDocument == null)
            {
                MessageBox.Show("No active Revit document. Please use Pull Changes to apply changes.",
                    "Apply Selected", MessageBoxButton.OK, MessageBoxImage.Warning);
                return;
            }

            var selectedElementIds = items
                .Where(i => i.IsSelected)
                .Select(i => i.ElementId)
                .ToHashSet();

            var selectedChanges = _currentChanges
                .Where(c => selectedElementIds.Contains(c.ElementId))
                .ToList();

            try
            {
                var applier = new ElementApplier(_currentDocument);
                var result = applier.ApplyChanges(selectedChanges);

                bool hasIssues = result.Errors.Count > 0
                                 || result.Warnings.Count > 0
                                 || result.UnsupportedElements.Count > 0
                                 || result.IgnoredAutogenerated.Count > 0;

                string msg = $"Applied: {result.AppliedCount}\n" +
                             $"Skipped: {result.SkippedCount}\n" +
                             $"Ignored autogenerated: {result.IgnoredAutogenerated.Count}\n" +
                             $"Unsupported/manual: {result.UnsupportedElements.Count}\n" +
                             $"Warnings: {result.WarningCount}\n" +
                             $"Failures: {result.ErrorCount}";

                if (result.UnsupportedElements.Count > 0)
                    msg += $"\n\nUnsupported/manual:\n" + string.Join("\n", result.UnsupportedElements.Take(2));
                if (result.Warnings.Count > 0)
                    msg += $"\n\nWarnings:\n" + string.Join("\n", result.Warnings.Take(2));
                if (result.Errors.Count > 0)
                    msg += $"\n\nFailures:\n" + string.Join("\n", result.Errors.Take(2));

                MessageBox.Show(msg,
                    hasIssues ? "Completed with issues" : "Success",
                    MessageBoxButton.OK,
                    hasIssues ? MessageBoxImage.Warning : MessageBoxImage.Information);
            }
            catch (Exception ex)
            {
                MessageBox.Show($"Failed to apply changes: {ex.Message}", "Error",
                    MessageBoxButton.OK, MessageBoxImage.Error);
            }
        }

        private List<ChangeItem> BuildChangeItems(List<Change> changes)
        {
            var items = new List<ChangeItem>();
            if (changes == null || changes.Count == 0)
            {
                items.Add(new ChangeItem
                {
                    ChangeType = "-",
                    StatusColor = new SolidColorBrush(Color.FromRgb(160, 160, 160)),
                    ElementType = "No changes",
                    Description = "No changes available",
                    Details = "",
                    IsSelected = false
                });
                return items;
            }

            foreach (var change in changes)
            {
                items.Add(new ChangeItem
                {
                    ChangeType = GetShortChangeType(change.ChangeType),
                    StatusColor = GetStatusColor(change.ChangeType),
                    ElementType = $"{change.Category}: {change.Type}",
                    Description = BuildDescription(change),
                    Details = BuildDetails(change),
                    ElementId = change.ElementId,
                    IsSelected = true
                });
            }

            return items;
        }

        private static (int added, int modified, int deleted) Summarize(List<Change> changes)
        {
            if (changes == null) return (0, 0, 0);
            return (
                changes.Count(c => c.ChangeType == "added"),
                changes.Count(c => c.ChangeType == "modified"),
                changes.Count(c => c.ChangeType == "deleted")
            );
        }

        private static string GetShortChangeType(string changeType)
        {
            switch (changeType)
            {
                case "added": return "ADD";
                case "modified": return "MOD";
                case "deleted": return "DEL";
                default: return changeType?.ToUpperInvariant() ?? "-";
            }
        }

        private static SolidColorBrush GetStatusColor(string changeType)
        {
            switch (changeType)
            {
                case "added": 
                    return new SolidColorBrush(Color.FromRgb(40, 167, 69));
                case "modified": 
                    return new SolidColorBrush(Color.FromRgb(255, 193, 7));
                case "deleted": 
                    return new SolidColorBrush(Color.FromRgb(220, 53, 69));
                default: 
                    return new SolidColorBrush(Color.FromRgb(160, 160, 160));
            }
        }

        private static string BuildDescription(Change change)
        {
            switch (change.ChangeType)
            {
                case "added":
                    return "Element added";
                case "modified":
                    return "Element modified";
                case "deleted":
                    return "Element deleted";
                default:
                    return "Change detected";
            }
        }

        private static string BuildDetails(Change change)
        {
            var details = new List<string>();
            if (change.ParameterChanges != null && change.ParameterChanges.Count > 0)
            {
                var preview = change.ParameterChanges.Take(3)
                    .Select(p => $"{p.Name}: {p.OldValue} â†’ {p.NewValue}");
                details.Add(string.Join("; ", preview));
            }
            if (change.GeometryChanged) details.Add("Geometry changed");
            if (change.LocationChanged) details.Add("Location changed");
            return string.Join(" | ", details);
        }

        public class ChangeItem : INotifyPropertyChanged
        {
            private bool _isSelected;

            public string ChangeType { get; set; }
            public Brush StatusColor { get; set; }
            public string ElementType { get; set; }
            public string Description { get; set; }
            public string Details { get; set; }
            public string ElementId { get; set; }

            public bool IsSelected
            {
                get => _isSelected;
                set
                {
                    _isSelected = value;
                    PropertyChanged?.Invoke(this, new PropertyChangedEventArgs(nameof(IsSelected)));
                }
            }

            public event PropertyChangedEventHandler PropertyChanged;
        }
    }
}

