using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Text.RegularExpressions;

namespace RevitVersionControl.Services
{
    internal static class ApplyResultMessageBuilder
    {
        public static string Build(ElementApplier.ApplyResult result, int detailLimit = 3)
        {
            if (result == null)
                return "No apply result available.";

            var builder = new StringBuilder();
            builder.AppendLine($"Applied: {result.AppliedCount}");
            builder.AppendLine($"Skipped: {result.SkippedCount}");
            builder.AppendLine($"Payload-satisfied: {result.PayloadSatisfiedCount}");
            builder.AppendLine($"Ignored autogenerated: {result.IgnoredAutogeneratedCount}");
            builder.AppendLine($"Unsupported/manual: {result.UnsupportedElements.Count}");
            builder.AppendLine($"Warnings: {result.WarningCount}");
            builder.Append($"Failures: {result.ErrorCount}");

            AppendSection(builder, "Unsupported/manual", result.UnsupportedElements, detailLimit);
            AppendSection(builder, "Warnings", result.Warnings, detailLimit);
            AppendSection(builder, "Failures", result.Errors, detailLimit);

            return builder.ToString();
        }

        private static void AppendSection(StringBuilder builder, string title, IEnumerable<string> items, int detailLimit)
        {
            var cleaned = (items ?? Enumerable.Empty<string>())
                .Select(SanitizeForUi)
                .Where(text => !string.IsNullOrWhiteSpace(text))
                .Distinct()
                .Take(detailLimit + 1)
                .ToList();

            if (cleaned.Count == 0)
                return;

            builder.AppendLine();
            builder.AppendLine();
            builder.AppendLine(title + ":");
            foreach (string item in cleaned.Take(detailLimit))
                builder.AppendLine(item);

            if (cleaned.Count > detailLimit)
                builder.Append("...");
        }

        private static string SanitizeForUi(string message)
        {
            if (string.IsNullOrWhiteSpace(message))
                return null;

            string text = message.Trim();
            text = Regex.Replace(text, @"^\[[^\]]+\]\s*", string.Empty);
            text = Regex.Replace(text, @"^(Add|Delete|Modified?)\s+failed\s+for\s+[^:]+:\s*", string.Empty, RegexOptions.IgnoreCase);
            text = Regex.Replace(text, @"^(Add|Delete|Modified?)\s*:\s*Element\s+[^ ]+\s*", string.Empty, RegexOptions.IgnoreCase);
            text = text.Replace(
                "Satisfied by grouped payload import. The copied element was not matched one-to-one, but the bundle imported successfully.",
                "Imported with payload bundle.");
            text = text.Replace(
                "Payload copy succeeded, but the copied element could not be identified.",
                "Imported with payload bundle.");

            return text.Trim();
        }
    }
}
