using System;
using System.Collections.Generic;
using System.Linq;
using Autodesk.Revit.DB;
using Newtonsoft.Json.Linq;

namespace RevitVersionControl.Services
{
    public class ElementApplier
    {
        private readonly Document _document;
        private readonly string _projectId;
        private readonly ElementCreator _creator;
        private readonly PayloadImportService _payloadImporter;
        private int _appliedCount;
        private int _skippedCount;
        private List<string> _errors;
        private List<string> _warnings;
        private List<string> _unsupportedElements;
        private List<string> _ignoredAutogenerated;
        private List<string> _payloadSatisfiedByBundle;

        public ElementApplier(Document document, string projectId = null)
        {
            _document = document;
            _projectId = projectId;
            _creator = new ElementCreator(document);
            _payloadImporter = new PayloadImportService(document);
        }

        public class ApplyResult
        {
            public bool Success { get; set; }
            public int AppliedCount { get; set; }
            public int SkippedCount { get; set; }
            public int ErrorCount { get; set; }
            public int WarningCount { get; set; }
            public int IgnoredAutogeneratedCount { get; set; }
            public int PayloadSatisfiedCount { get; set; }
            public List<string> Errors { get; set; }
            public List<string> Warnings { get; set; }
            public List<string> UnsupportedElements { get; set; }
            public List<string> IgnoredAutogenerated { get; set; }
            public List<string> PayloadSatisfiedByBundle { get; set; }
            public string Summary { get; set; }
        }

        public List<string> GetMissingFamilies(List<Change> changes) =>
            _creator.GetMissingFamilies(changes);

        public ApplyResult ApplyChanges(List<Change> changes)
        {
            _appliedCount = 0;
            _skippedCount = 0;
            _errors = new List<string>();
            _warnings = new List<string>();
            _unsupportedElements = new List<string>();
            _ignoredAutogenerated = new List<string>();
            _payloadSatisfiedByBundle = new List<string>();

            if (changes == null || changes.Count == 0)
            {
                return new ApplyResult
                {
                    Success = true,
                    AppliedCount = 0,
                    SkippedCount = 0,
                    ErrorCount = 0,
                    WarningCount = 0,
                    IgnoredAutogeneratedCount = 0,
                    PayloadSatisfiedCount = 0,
                    Errors = new List<string>(),
                    Warnings = new List<string>(),
                    UnsupportedElements = new List<string>(),
                    IgnoredAutogenerated = new List<string>(),
                    PayloadSatisfiedByBundle = new List<string>(),
                    Summary = "No changes to apply."
                };
            }

            using (Transaction trans = new Transaction(_document, "Apply Remote Changes"))
            {
                trans.Start();
                try
                {
                    var preHandledAdds = ApplyPayloadBackedAdds(changes);
                    foreach (var change in changes)
                    {
                        string changeKey = GetChangeTrackingKey(change);
                        if (!string.IsNullOrWhiteSpace(changeKey) && preHandledAdds.Contains(changeKey))
                            continue;

                        if (change.ChangeType == "deleted")
                            ApplyDelete(change);
                        else if (change.ChangeType == "modified")
                            ApplyModified(change);
                        else if (change.ChangeType == "added")
                            ApplyAdd(change);
                    }

                    trans.Commit();

                    return new ApplyResult
                    {
                        Success = true,
                        AppliedCount = _appliedCount,
                        SkippedCount = _skippedCount,
                        ErrorCount = _errors.Count,
                        WarningCount = _warnings.Count,
                        IgnoredAutogeneratedCount = _ignoredAutogenerated.Count,
                        PayloadSatisfiedCount = _payloadSatisfiedByBundle.Count,
                        Errors = _errors,
                        Warnings = _warnings,
                        UnsupportedElements = _unsupportedElements,
                        IgnoredAutogenerated = _ignoredAutogenerated,
                        PayloadSatisfiedByBundle = _payloadSatisfiedByBundle,
                        Summary = $"Applied {_appliedCount}, Payload-satisfied {_payloadSatisfiedByBundle.Count}, Skipped {_skippedCount}, Ignored {_ignoredAutogenerated.Count}, Unsupported {_unsupportedElements.Count}, Warnings {_warnings.Count}, Errors {_errors.Count}"
                    };
                }
                catch (Exception ex)
                {
                    trans.RollBack();
                    _errors.Add($"Transaction failed: {ex.Message}");
                    return new ApplyResult
                    {
                        Success = false,
                        AppliedCount = _appliedCount,
                        SkippedCount = _skippedCount,
                        ErrorCount = _errors.Count,
                        WarningCount = _warnings.Count,
                        IgnoredAutogeneratedCount = _ignoredAutogenerated.Count,
                        PayloadSatisfiedCount = _payloadSatisfiedByBundle.Count,
                        Errors = _errors,
                        Warnings = _warnings,
                        UnsupportedElements = _unsupportedElements,
                        IgnoredAutogenerated = _ignoredAutogenerated,
                        PayloadSatisfiedByBundle = _payloadSatisfiedByBundle,
                        Summary = $"Failed. Rolled back. Error: {ex.Message}"
                    };
                }
            }
        }

        private void ApplyDelete(Change change)
        {
            try
            {
                Element element = ResolveElement(change);

                if (element != null && !element.Pinned)
                {
                    _document.Delete(element.Id);
                    _appliedCount++;
                    return;
                }

                if (element == null && IsIgnoredAutogenerated(change))
                {
                    RecordIgnoredAutogenerated(change, "Delete skipped because Revit regenerated or removed this internal dependent element automatically.");
                    return;
                }

                _skippedCount++;
                _errors.Add(element == null
                    ? $"Delete: Element {change.ElementId} not found"
                    : $"Delete: Element {change.ElementId} is pinned");
            }
            catch (Exception ex)
            {
                if (IsIgnoredAutogenerated(change))
                {
                    RecordIgnoredAutogenerated(change, $"Delete skipped for autogenerated/internal element: {ex.Message}");
                    return;
                }

                _skippedCount++;
                _errors.Add($"Delete failed for {change.ElementId}: {ex.Message}");
            }
        }

        private void ApplyModified(Change change)
        {
            try
            {
                Element element = ResolveElement(change);

                if (element == null)
                {
                    if (IsIgnoredAutogenerated(change))
                    {
                        RecordIgnoredAutogenerated(change, "Modify skipped because this autogenerated/internal element is not tracked independently in the target model.");
                        return;
                    }

                    _skippedCount++;
                    _errors.Add($"Modified: Element {change.ElementId} not found");
                    return;
                }

                TryEnsureRepoGuid(element, change.RepoGuid);

                bool modified = false;
                var oldData = change.OldData != null ? JObject.FromObject(change.OldData) : null;
                var newData = change.NewData != null ? JObject.FromObject(change.NewData) : null;

                modified |= ApplyTypeChange(element, oldData, newData, out string appliedTypeDisplayName);

                if (change.ParameterChanges != null && change.ParameterChanges.Count > 0)
                    modified |= ApplyParameterChanges(element, change.ParameterChanges, appliedTypeDisplayName);

                if (change.LocationChanged && newData != null)
                    modified |= ApplyLocationChange(element, newData);

                if (modified)
                    _appliedCount++;
                else
                    _skippedCount++;
            }
            catch (Exception ex)
            {
                if (IsIgnoredAutogenerated(change))
                {
                    RecordIgnoredAutogenerated(change, $"Modify skipped for autogenerated/internal element: {ex.Message}");
                    return;
                }

                _skippedCount++;
                _errors.Add($"Modified failed for {change.ElementId}: {ex.Message}");
            }
        }

        private void ApplyAdd(Change change)
        {
            try
            {
                if (change.NewData == null)
                {
                    _skippedCount++;
                    _errors.Add($"Add: No data for element {change.ElementId}");
                    return;
                }

                Element existing = ResolveElement(change);
                if (existing != null)
                {
                    TryEnsureRepoGuid(existing, change.RepoGuid);
                    _appliedCount++;
                    return;
                }

                // Additional duplicate check: look for an element of the same type at the same location
                // This prevents overlap errors when switching branches with the same physical elements
                // that have different UniqueIds
                Element locationDuplicate = FindExistingByTypeAndLocation(change);
                if (locationDuplicate != null)
                {
                    TryEnsureRepoGuid(locationDuplicate, change.RepoGuid);
                    _appliedCount++;
                    _warnings.Add($"Add: Element {change.ElementId} already exists at location (mapped by type+location).");
                    return;
                }

                if (IsIgnoredAutogenerated(change))
                {
                    RecordIgnoredAutogenerated(change, "Add skipped because this element category is Revit-generated/internal and should not be recreated independently.");
                    return;
                }

                var newData = JObject.FromObject(change.NewData);
                CreationResult result = TryCreateFromPayload(change, newData)
                    ?? _creator.Create(newData);

                if (result.IsUnsupported)
                {
                    _skippedCount++;
                    _unsupportedElements.Add($"[{change.ElementId}] {result.Reason}");
                    return;
                }

                if (result.Element == null)
                {
                    _skippedCount++;
                    _errors.Add($"Add failed for {change.ElementId}: {result.Reason}");
                    return;
                }

                string repoGuid = change.RepoGuid ?? newData["repoGuid"]?.ToString();
                TryEnsureRepoGuid(result.Element, repoGuid);

                var parameters = newData["parameters"] as JObject;
                if (parameters != null)
                    ApplyParametersFromJObject(result.Element, parameters);

                if (!string.IsNullOrEmpty(result.Reason))
                    _warnings.Add($"Add warning for {change.ElementId}: {result.Reason}");

                _appliedCount++;
            }
            catch (Exception ex)
            {
                if (IsIgnoredAutogenerated(change))
                {
                    RecordIgnoredAutogenerated(change, $"Add skipped for autogenerated/internal element: {ex.Message}");
                    return;
                }

                _skippedCount++;
                _errors.Add($"Add failed for {change.ElementId}: {ex.Message}");
            }
        }

        private HashSet<string> ApplyPayloadBackedAdds(IEnumerable<Change> changes)
        {
            var handled = new HashSet<string>(StringComparer.OrdinalIgnoreCase);
            var payloadGroups = new Dictionary<string, PayloadBatchGroup>(StringComparer.OrdinalIgnoreCase);

            foreach (var change in changes ?? Enumerable.Empty<Change>())
            {
                if (!string.Equals(change?.ChangeType, "added", StringComparison.OrdinalIgnoreCase))
                    continue;

                if (!PayloadSupportService.TryGetPayloadReference(change, out PayloadRef payloadRef, out string marker))
                    continue;

                if (payloadRef == null || string.IsNullOrWhiteSpace(payloadRef.PayloadId))
                    continue;

                string changeKey = GetChangeTrackingKey(change);
                if (string.IsNullOrWhiteSpace(changeKey))
                    continue;

                if (!payloadGroups.TryGetValue(payloadRef.PayloadId, out PayloadBatchGroup group))
                {
                    group = new PayloadBatchGroup { PayloadRef = payloadRef };
                    payloadGroups[payloadRef.PayloadId] = group;
                }

                group.ChangeKeys.Add(changeKey);
                group.ChangeByKey[changeKey] = change;
                group.Requests.Add(new PayloadImportRequest
                {
                    RequestKey = changeKey,
                    Marker = marker,
                    RepoGuid = change.RepoGuid ?? ReadRepoGuid(change.NewData),
                    ElementId = change.ElementId,
                    Category = ResolveChangeCategory(change),
                });
            }

            foreach (PayloadBatchGroup group in payloadGroups.Values)
            {
                var batchResults = _payloadImporter.CreateFromPayloadBatch(_projectId, group.PayloadRef, group.Requests);
                foreach (string changeKey in group.ChangeKeys)
                {
                    if (!batchResults.TryGetValue(changeKey, out CreationResult result))
                        continue;

                    handled.Add(changeKey);
                    ProcessPayloadBatchResult(group.ChangeByKey[changeKey], result);
                }
            }

            return handled;
        }

        private void ProcessPayloadBatchResult(Change change, CreationResult result)
        {
            if (result == null)
            {
                _skippedCount++;
                _errors.Add($"Add failed for {change.ElementId}: Payload copy did not return a result.");
                return;
            }

            if (result.IsUnsupported)
            {
                _skippedCount++;
                _unsupportedElements.Add($"[{change.ElementId}] {result.Reason}");
                return;
            }

            if (result.IsSatisfiedByBundle)
            {
                _payloadSatisfiedByBundle.Add($"{BuildChangeDisplayLabel(change)}: {result.Reason}");
                return;
            }

            if (result.Element == null)
            {
                _skippedCount++;
                _errors.Add($"Add failed for {change.ElementId}: {result.Reason}");
                return;
            }

            string repoGuid = change.RepoGuid ?? ReadRepoGuid(change.NewData);
            TryEnsureRepoGuid(result.Element, repoGuid);

            if (change.NewData != null)
            {
                var parameters = JObject.FromObject(change.NewData)["parameters"] as JObject;
                if (parameters != null)
                    ApplyParametersFromJObject(result.Element, parameters);
            }

            if (!string.IsNullOrWhiteSpace(result.Reason))
                _warnings.Add($"Add warning for {change.ElementId}: {result.Reason}");

            _appliedCount++;
        }

        private bool ApplyParameterChanges(
            Element element,
            List<ParameterChange> paramChanges,
            string alreadyAppliedTypeDisplayName = null)
        {
            bool changed = false;
            foreach (var paramChange in paramChanges)
            {
                try
                {
                    Parameter param = element.LookupParameter(paramChange.Name);
                    if (param == null || param.IsReadOnly || paramChange.NewValue == null)
                        continue;

                    if (!string.IsNullOrEmpty(alreadyAppliedTypeDisplayName)
                        && string.Equals(paramChange.ElementName, alreadyAppliedTypeDisplayName, StringComparison.OrdinalIgnoreCase))
                    {
                        continue;
                    }

                    changed |= TryApplyParameterValue(
                        param,
                        paramChange.Name,
                        paramChange.NewValue,
                        paramChange.ElementName);
                }
                catch (Exception ex)
                {
                    _errors.Add($"Parameter '{paramChange.Name}': {ex.Message}");
                }
            }
            return changed;
        }

        private void ApplyParametersFromJObject(Element element, JObject parameters)
        {
            foreach (var prop in parameters.Properties())
            {
                try
                {
                    var paramData = prop.Value as JObject;
                    if (paramData == null)
                        continue;

                    Parameter param = element.LookupParameter(prop.Name);
                    if (param == null || param.IsReadOnly)
                        continue;

                    var value = paramData["value"];
                    if (value == null)
                        continue;

                    string elementName = paramData["elementName"]?.ToString();
                    TryApplyParameterValue(param, prop.Name, value, elementName);
                }
                catch (Exception ex)
                {
                    _errors.Add($"Parameter '{prop.Name}': {ex.Message}");
                }
            }
        }

        private bool TryApplyParameterValue(
            Parameter param,
            string parameterName,
            object newValue,
            string elementName)
        {
            switch (param.StorageType)
            {
                case StorageType.Double:
                    if (double.TryParse(newValue.ToString(), out double d))
                    {
                        param.Set(d);
                        return true;
                    }
                    break;

                case StorageType.Integer:
                    if (int.TryParse(newValue.ToString(), out int i))
                    {
                        param.Set(i);
                        return true;
                    }
                    break;

                case StorageType.String:
                    param.Set(newValue.ToString());
                    return true;

                case StorageType.ElementId:
                    if (!string.IsNullOrEmpty(elementName))
                    {
                        ElementId resolvedId = ResolveElementIdByName(elementName);
                        if (resolvedId != null)
                        {
                            param.Set(resolvedId);
                            return true;
                        }

                        _errors.Add(
                            $"Parameter '{parameterName}': could not find element named '{elementName}' in this model.");
                        return false;
                    }

                    if (int.TryParse(newValue.ToString(), out int eid))
                    {
                        param.Set(new ElementId(eid));
                        return true;
                    }
                    break;
            }

            return false;
        }

        private bool ApplyTypeChange(
            Element element,
            JObject oldData,
            JObject newData,
            out string appliedTypeDisplayName)
        {
            appliedTypeDisplayName = null;
            if (newData == null)
                return false;

            string newFamilyName = newData["familyName"]?.ToString();
            string newTypeName = newData["typeName"]?.ToString();
            string oldFamilyName = oldData?["familyName"]?.ToString();
            string oldTypeName = oldData?["typeName"]?.ToString();

            if (string.Equals(newFamilyName, oldFamilyName, StringComparison.OrdinalIgnoreCase)
                && string.Equals(newTypeName, oldTypeName, StringComparison.OrdinalIgnoreCase))
            {
                return false;
            }

            if (string.IsNullOrWhiteSpace(newTypeName))
                return false;

            ElementId targetTypeId = ResolveElementTypeId(newFamilyName, newTypeName);
            if (targetTypeId == null)
            {
                _errors.Add($"Type change: could not find target type '{BuildElementTypeDisplayName(newFamilyName, newTypeName)}' in this model.");
                return false;
            }

            ElementId currentTypeId = element.GetTypeId();
            if (currentTypeId != ElementId.InvalidElementId && currentTypeId == targetTypeId)
            {
                appliedTypeDisplayName = BuildElementTypeDisplayName(newFamilyName, newTypeName);
                return false;
            }

            try
            {
                element.ChangeTypeId(targetTypeId);
                appliedTypeDisplayName = BuildElementTypeDisplayName(newFamilyName, newTypeName);
                return true;
            }
            catch (Exception ex)
            {
                _errors.Add($"Type change failed for {element.UniqueId}: {ex.Message}");
                return false;
            }
        }

        private ElementId ResolveElementIdByName(string elementName)
        {
            if (string.IsNullOrEmpty(elementName))
                return null;

            try
            {
                var typeMatch = new FilteredElementCollector(_document)
                    .OfClass(typeof(ElementType))
                    .Cast<ElementType>()
                    .FirstOrDefault(t =>
                        (t.FamilyName + " : " + t.Name) == elementName ||
                        t.Name == elementName);

                if (typeMatch != null)
                    return typeMatch.Id;

                var namedMatch = new FilteredElementCollector(_document)
                    .WhereElementIsNotElementType()
                    .Cast<Element>()
                    .FirstOrDefault(e =>
                        !string.IsNullOrEmpty(e.Name) && e.Name == elementName);

                if (namedMatch != null)
                    return namedMatch.Id;
            }
            catch
            {
                return null;
            }

            return null;
        }

        private ElementId ResolveElementTypeId(string familyName, string typeName)
        {
            if (string.IsNullOrWhiteSpace(typeName))
                return null;

            try
            {
                var exactMatch = new FilteredElementCollector(_document)
                    .OfClass(typeof(ElementType))
                    .Cast<ElementType>()
                    .FirstOrDefault(t =>
                        string.Equals(t.Name, typeName, StringComparison.OrdinalIgnoreCase)
                        && string.Equals(t.FamilyName ?? string.Empty, familyName ?? string.Empty, StringComparison.OrdinalIgnoreCase));

                if (exactMatch != null)
                    return exactMatch.Id;

                var nameOnlyMatch = new FilteredElementCollector(_document)
                    .OfClass(typeof(ElementType))
                    .Cast<ElementType>()
                    .FirstOrDefault(t =>
                        string.Equals(t.Name, typeName, StringComparison.OrdinalIgnoreCase));

                if (nameOnlyMatch != null)
                    return nameOnlyMatch.Id;
            }
            catch
            {
                return null;
            }

            return null;
        }

        private static string BuildElementTypeDisplayName(string familyName, string typeName)
        {
            if (string.IsNullOrWhiteSpace(familyName))
                return typeName ?? string.Empty;
            return familyName + " : " + typeName;
        }

        private bool ApplyLocationChange(Element element, JObject newData)
        {
            try
            {
                var locationData = newData["location"] as JObject;
                if (locationData == null)
                    return false;

                string locationType = locationData["type"]?.ToString();
                Location location = element.Location;
                if (location == null)
                    return false;

                if (location is LocationPoint locPoint && locationType == "point")
                {
                    var point = locationData["point"] as JObject;
                    if (point == null)
                        return false;

                    locPoint.Point = new XYZ(
                        point["x"]?.Value<double>() ?? 0,
                        point["y"]?.Value<double>() ?? 0,
                        point["z"]?.Value<double>() ?? 0);

                    if (locationData["rotation"] != null &&
                        double.TryParse(locationData["rotation"].ToString(), out double rotation))
                    {
                        double diff = rotation - locPoint.Rotation;
                        if (Math.Abs(diff) > 0.0001)
                        {
                            Line axis = Line.CreateBound(locPoint.Point, locPoint.Point + XYZ.BasisZ);
                            ElementTransformUtils.RotateElement(_document, element.Id, axis, diff);
                        }
                    }
                    return true;
                }

                if (location is LocationCurve locCurve && locationType == "curve")
                {
                    var startPt = locationData["startPoint"] as JObject;
                    var endPt = locationData["endPoint"] as JObject;
                    if (startPt == null || endPt == null)
                        return false;

                    locCurve.Curve = Line.CreateBound(
                        new XYZ(startPt["x"]?.Value<double>() ?? 0, startPt["y"]?.Value<double>() ?? 0, startPt["z"]?.Value<double>() ?? 0),
                        new XYZ(endPt["x"]?.Value<double>() ?? 0, endPt["y"]?.Value<double>() ?? 0, endPt["z"]?.Value<double>() ?? 0));
                    return true;
                }

                return false;
            }
            catch (Exception ex)
            {
                _errors.Add($"Location change failed: {ex.Message}");
                return false;
            }
        }

        private bool IsIgnoredAutogenerated(Change change)
        {
            return SyncCategoryRules.IsAutoGeneratedOrInternalCategory(ResolveChangeCategory(change));
        }

        private void RecordIgnoredAutogenerated(Change change, string reason)
        {
            _skippedCount++;
            _ignoredAutogenerated.Add($"[{change.ElementId}] {ResolveChangeCategory(change)}: {reason}");
        }

        private string ResolveChangeCategory(Change change)
        {
            if (!string.IsNullOrWhiteSpace(change?.Category))
                return change.Category;

            try
            {
                if (change?.NewData != null)
                {
                    var newData = JObject.FromObject(change.NewData);
                    string category = newData["category"]?.ToString();
                    if (!string.IsNullOrWhiteSpace(category))
                        return category;
                }

                if (change?.OldData != null)
                {
                    var oldData = JObject.FromObject(change.OldData);
                    string category = oldData["category"]?.ToString();
                    if (!string.IsNullOrWhiteSpace(category))
                        return category;
                }
            }
            catch
            {
                // Ignore malformed category payloads.
            }

            return "Unknown";
        }

        private Element ResolveElement(Change change)
        {
            if (change == null)
                return null;

            // Try RepoGuid + UniqueId
            Element el = RepoGuidService.FindElement(_document, change.RepoGuid, change.ElementId);
            if (el != null) return el;

            // Fallback: try numeric ID
            if (!string.IsNullOrEmpty(change.ElementId) && long.TryParse(change.ElementId, out long numId))
            {
                try { el = _document.GetElement(new ElementId(numId)); } catch { }
            }

            return el;
        }

        /// <summary>
        /// Find an existing element of the same category/type at approximately the same location.
        /// This prevents duplicate creation when branches have the same physical element
        /// with different UniqueIds.
        /// </summary>
        private Element FindExistingByTypeAndLocation(Change change)
        {
            if (change?.NewData == null) return null;

            try
            {
                var newData = JObject.FromObject(change.NewData);
                string category = newData["category"]?.ToString();
                string typeName = newData["typeName"]?.ToString();
                var locationObj = newData["location"] as JObject;
                if (string.IsNullOrEmpty(category) || locationObj == null) return null;

                string locType = locationObj["type"]?.ToString();
                XYZ targetPoint = null;

                if (locType == "point")
                {
                    var pt = locationObj["point"] as JObject;
                    if (pt != null)
                    {
                        double.TryParse(pt["x"]?.ToString(), out double x);
                        double.TryParse(pt["y"]?.ToString(), out double y);
                        double.TryParse(pt["z"]?.ToString(), out double z);
                        targetPoint = new XYZ(x, y, z);
                    }
                }
                else if (locType == "curve")
                {
                    var sp = locationObj["startPoint"] as JObject;
                    if (sp != null)
                    {
                        double.TryParse(sp["x"]?.ToString(), out double sx);
                        double.TryParse(sp["y"]?.ToString(), out double sy);
                        double.TryParse(sp["z"]?.ToString(), out double sz);
                        targetPoint = new XYZ(sx, sy, sz);
                    }
                }

                if (targetPoint == null) return null;

                // Search for elements of the same category near this location
                var collector = new FilteredElementCollector(_document)
                    .WhereElementIsNotElementType()
                    .WhereElementIsViewIndependent();

                foreach (Element el in collector)
                {
                    if (el?.Category?.Name != category) continue;
                    if (typeName != null && el.Name != typeName) continue;

                    Location loc = el.Location;
                    XYZ elPoint = null;

                    if (loc is LocationPoint lp)
                        elPoint = lp.Point;
                    else if (loc is LocationCurve lc)
                        elPoint = lc.Curve.GetEndPoint(0);

                    if (elPoint == null) continue;

                    // Check if within ~0.1 feet tolerance
                    if (elPoint.DistanceTo(targetPoint) < 0.1)
                        return el;
                }
            }
            catch { }

            return null;
        }

        private CreationResult TryCreateFromPayload(Change change, JObject newData)
        {
            if (!PayloadSupportService.TryGetPayloadReference(change, out PayloadRef payloadRef, out string marker))
                return null;

            if (string.IsNullOrWhiteSpace(_projectId))
                return CreationResult.Failed("Payload-backed add requires project context for donor lookup.");

            string repoGuid = change.RepoGuid ?? newData?["repoGuid"]?.ToString();
            return _payloadImporter.CreateFromPayload(_projectId, payloadRef, marker, repoGuid);
        }

        private static void TryEnsureRepoGuid(Element element, string repoGuid)
        {
            if (element == null || string.IsNullOrWhiteSpace(repoGuid))
                return;

            string existing = RepoGuidService.GetRepoGuid(element);
            if (string.Equals(existing, repoGuid, StringComparison.OrdinalIgnoreCase))
                return;

            RepoGuidService.SetRepoGuid(element, repoGuid);
        }

        private static string GetChangeTrackingKey(Change change)
        {
            if (!string.IsNullOrWhiteSpace(change?.RepoGuid))
                return "repo:" + change.RepoGuid;

            if (!string.IsNullOrWhiteSpace(change?.ElementId))
                return "id:" + change.ElementId;

            return null;
        }

        private static string ReadRepoGuid(Dictionary<string, object> data)
        {
            if (data == null)
                return null;

            return data.TryGetValue("repoGuid", out object repoGuidValue)
                ? repoGuidValue?.ToString()
                : null;
        }

        private string BuildChangeDisplayLabel(Change change)
        {
            string category = ResolveChangeCategory(change);
            string type = change?.Type;

            if (!string.IsNullOrWhiteSpace(category) && !string.IsNullOrWhiteSpace(type))
                return category + ": " + type;

            if (!string.IsNullOrWhiteSpace(category))
                return category;

            return change?.ElementId ?? "Element";
        }

        private class PayloadBatchGroup
        {
            public PayloadRef PayloadRef { get; set; }
            public List<PayloadImportRequest> Requests { get; } = new List<PayloadImportRequest>();
            public Dictionary<string, Change> ChangeByKey { get; } =
                new Dictionary<string, Change>(StringComparer.OrdinalIgnoreCase);
            public List<string> ChangeKeys { get; } = new List<string>();
        }
    }
}
