using System;
using System.Linq;
using Autodesk.Revit.DB;
using Autodesk.Revit.UI;

namespace RevitVersionControl.Services
{
    public static class PullService
    {
        public static bool ExecutePullApply(
            UIApplication uiApp,
            string projectId,
            string trackedModelId,
            string targetCommit,
            string targetBranchName,
            PullResult pullResult,
            bool silentMode = false)
        {
            Document doc = uiApp.ActiveUIDocument.Document;

            System.Windows.Input.Mouse.OverrideCursor = System.Windows.Input.Cursors.Wait;
            ElementApplier.ApplyResult applyResponse = null;

            try
            {
                if (!PayloadSupportService.EnsurePayloadsAvailable(projectId, pullResult.Changes, out string payloadError))
                {
                    if (!silentMode)
                        TaskDialog.Show("Error", payloadError);
                    return false;
                }

                var applier = new ElementApplier(doc, projectId);
                applyResponse = applier.ApplyChanges(pullResult.Changes);
            }
            finally
            {
                System.Windows.Input.Mouse.OverrideCursor = null;
            }

            if (applyResponse.Success)
            {
                DocumentSyncStateService.SaveState(doc.PathName, projectId, trackedModelId, targetCommit, targetBranchName);
                
                try
                {
                    var extractor = new ElementExtractor(doc);
                    var extractionOptions = new ExtractionOptions
                    {
                        BatchSize = 200,
                        PauseMilliseconds = 10,
                        IncludeGeometry = true,
                        LogProgress = true
                    };
                    var currentElements = extractor.ExtractAllElements(extractionOptions);
                    var cachedSnapshot = new ElementSnapshot
                    {
                        Version = "1.0",
                        ProjectId = projectId,
                        ModelId = trackedModelId,
                        Timestamp = DateTime.UtcNow,
                        UserName = uiApp.Application.Username,
                        CommitMessage = $"Cached after pull to {targetCommit}",
                        Elements = currentElements.Cast<object>().ToList(),
                        ParentCommit = targetCommit
                    };
                    SnapshotCacheService.SaveSnapshot(projectId, trackedModelId, targetCommit, cachedSnapshot);
                }
                catch { }

                if (!silentMode)
                {
                    bool hasIssues = applyResponse.Errors.Count > 0
                                     || applyResponse.Warnings.Count > 0
                                     || applyResponse.UnsupportedElements.Count > 0
                                     || applyResponse.IgnoredAutogenerated.Count > 0;

                    string title = hasIssues ? "Completed with issues" : "Success";
                    TaskDialog.Show(title, ApplyResultMessageBuilder.Build(applyResponse));

                    if (hasIssues)
                    {
                        System.Diagnostics.Debug.WriteLine("\n=== APPLY CHANGES DETAILED LOG ===");
                        foreach (var satisfied in applyResponse.PayloadSatisfiedByBundle)
                            System.Diagnostics.Debug.WriteLine("[PAYLOAD-SATISFIED] " + satisfied);
                        foreach (var ignored in applyResponse.IgnoredAutogenerated)
                            System.Diagnostics.Debug.WriteLine("[IGNORED] " + ignored);
                        foreach (var unsupported in applyResponse.UnsupportedElements)
                            System.Diagnostics.Debug.WriteLine("[UNSUPPORTED] " + unsupported);
                        foreach (var warning in applyResponse.Warnings)
                            System.Diagnostics.Debug.WriteLine("[WARNING] " + warning);
                        foreach (var error in applyResponse.Errors)
                            System.Diagnostics.Debug.WriteLine("[ERROR] " + error);
                        System.Diagnostics.Debug.WriteLine("=================================\n");
                    }
                }

                return true;
            }
            else
            {
                if (!silentMode)
                {
                    string errorMessage = "Failed to apply changes:\n\n";
                    if (applyResponse.Errors.Count > 0)
                    {
                        errorMessage += string.Join("\n", applyResponse.Errors.Take(5));
                        if (applyResponse.Errors.Count > 5)
                            errorMessage += $"\n\n... and {applyResponse.Errors.Count - 5} more errors";
                    }
                    else
                    {
                        errorMessage += "Unknown error occurred.";
                    }

                    TaskDialog.Show("Error", errorMessage);
                }
                return false;
            }
        }
    }
}
