using System;
using System.Collections.Generic;

namespace RevitVersionControl.Services
{
    public static class SyncCategoryRules
    {
        private static readonly HashSet<string> _autoGeneratedOrInternalCategories =
            new HashSet<string>(StringComparer.OrdinalIgnoreCase)
            {
                "Analytical Nodes",
                "Analytical Links",
                "Analytical Floors",
                "Analytical Walls",
                "Analytical Columns",
                "Analytical Beams",
                "Analytical Braces",
                "Analytical Foundation Slabs",
                "Analytical Isolated Foundations",
                "Analytical Wall Foundations",
                "Analytical Spaces",
                "Analytical Surfaces",
                "Structural Connections",
                "Coordination Model",
                "gbXML Faces",
                "System-defined",
                "Wall Sweeps",
                "Fascias",
                "Gutters",
                "Slab Edges",
                "Reveals",
                "Structural Stiffeners",
            };

        private static readonly HashSet<string> _payloadBackedCategories =
            new HashSet<string>(StringComparer.OrdinalIgnoreCase)
            {
                "Stairs",
                "Railings",
                "Railing",
                "Model Text",
            };

        private static readonly HashSet<string> _nativeCreateSafeCategories =
            new HashSet<string>(StringComparer.OrdinalIgnoreCase)
            {
                "Walls",
                "Floors",
                "Roofs",
                "Levels",
                "Grids",
                "Structural Columns",
                "Columns",
                "Structural Framing",
                "Rooms",
                "Ducts",
                "Pipes",
                "Cable Trays",
                "Conduits",
            };

        public static bool IsAutoGeneratedOrInternalCategory(string category)
        {
            if (string.IsNullOrWhiteSpace(category))
                return true;

            return _autoGeneratedOrInternalCategories.Contains(category);
        }

        public static bool IsPayloadBackedCategory(string category)
        {
            if (string.IsNullOrWhiteSpace(category))
                return false;

            return _payloadBackedCategories.Contains(category);
        }

        public static bool IsSafeNativeCreateCategory(string category)
        {
            if (string.IsNullOrWhiteSpace(category))
                return false;

            return _nativeCreateSafeCategories.Contains(category);
        }

        public static bool ShouldUsePayloadForAddedElement(string category)
        {
            if (string.IsNullOrWhiteSpace(category))
                return false;

            if (IsAutoGeneratedOrInternalCategory(category))
                return false;

            if (IsPayloadBackedCategory(category))
                return true;

            return !IsSafeNativeCreateCategory(category);
        }
    }
}
